// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bkotos/listello/internal/listello-instance-context/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockListelloInstanceService creates a new instance of MockListelloInstanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListelloInstanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListelloInstanceService {
	mock := &MockListelloInstanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListelloInstanceService is an autogenerated mock type for the ListelloInstanceService type
type MockListelloInstanceService struct {
	mock.Mock
}

type MockListelloInstanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListelloInstanceService) EXPECT() *MockListelloInstanceService_Expecter {
	return &MockListelloInstanceService_Expecter{mock: &_m.Mock}
}

// CreateInstance provides a mock function for the type MockListelloInstanceService
func (_mock *MockListelloInstanceService) CreateInstance() (domain.ListelloInstance, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateInstance")
	}

	var r0 domain.ListelloInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (domain.ListelloInstance, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() domain.ListelloInstance); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.ListelloInstance)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListelloInstanceService_CreateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstance'
type MockListelloInstanceService_CreateInstance_Call struct {
	*mock.Call
}

// CreateInstance is a helper method to define mock.On call
func (_e *MockListelloInstanceService_Expecter) CreateInstance() *MockListelloInstanceService_CreateInstance_Call {
	return &MockListelloInstanceService_CreateInstance_Call{Call: _e.mock.On("CreateInstance")}
}

func (_c *MockListelloInstanceService_CreateInstance_Call) Run(run func()) *MockListelloInstanceService_CreateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListelloInstanceService_CreateInstance_Call) Return(listelloInstance domain.ListelloInstance, err error) *MockListelloInstanceService_CreateInstance_Call {
	_c.Call.Return(listelloInstance, err)
	return _c
}

func (_c *MockListelloInstanceService_CreateInstance_Call) RunAndReturn(run func() (domain.ListelloInstance, error)) *MockListelloInstanceService_CreateInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type MockListelloInstanceService
func (_mock *MockListelloInstanceService) GetInstance() (*domain.ListelloInstance, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *domain.ListelloInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*domain.ListelloInstance, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *domain.ListelloInstance); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ListelloInstance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListelloInstanceService_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type MockListelloInstanceService_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
func (_e *MockListelloInstanceService_Expecter) GetInstance() *MockListelloInstanceService_GetInstance_Call {
	return &MockListelloInstanceService_GetInstance_Call{Call: _e.mock.On("GetInstance")}
}

func (_c *MockListelloInstanceService_GetInstance_Call) Run(run func()) *MockListelloInstanceService_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListelloInstanceService_GetInstance_Call) Return(listelloInstance *domain.ListelloInstance, err error) *MockListelloInstanceService_GetInstance_Call {
	_c.Call.Return(listelloInstance, err)
	return _c
}

func (_c *MockListelloInstanceService_GetInstance_Call) RunAndReturn(run func() (*domain.ListelloInstance, error)) *MockListelloInstanceService_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// SelectPersistenceLocation provides a mock function for the type MockListelloInstanceService
func (_mock *MockListelloInstanceService) SelectPersistenceLocation(location string) (domain.ListelloInstance, error) {
	ret := _mock.Called(location)

	if len(ret) == 0 {
		panic("no return value specified for SelectPersistenceLocation")
	}

	var r0 domain.ListelloInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.ListelloInstance, error)); ok {
		return returnFunc(location)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.ListelloInstance); ok {
		r0 = returnFunc(location)
	} else {
		r0 = ret.Get(0).(domain.ListelloInstance)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(location)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListelloInstanceService_SelectPersistenceLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectPersistenceLocation'
type MockListelloInstanceService_SelectPersistenceLocation_Call struct {
	*mock.Call
}

// SelectPersistenceLocation is a helper method to define mock.On call
//   - location string
func (_e *MockListelloInstanceService_Expecter) SelectPersistenceLocation(location any) *MockListelloInstanceService_SelectPersistenceLocation_Call {
	return &MockListelloInstanceService_SelectPersistenceLocation_Call{Call: _e.mock.On("SelectPersistenceLocation", location)}
}

func (_c *MockListelloInstanceService_SelectPersistenceLocation_Call) Run(run func(location string)) *MockListelloInstanceService_SelectPersistenceLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListelloInstanceService_SelectPersistenceLocation_Call) Return(listelloInstance domain.ListelloInstance, err error) *MockListelloInstanceService_SelectPersistenceLocation_Call {
	_c.Call.Return(listelloInstance, err)
	return _c
}

func (_c *MockListelloInstanceService_SelectPersistenceLocation_Call) RunAndReturn(run func(location string) (domain.ListelloInstance, error)) *MockListelloInstanceService_SelectPersistenceLocation_Call {
	_c.Call.Return(run)
	return _c
}
