// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package application_test

import (
	"github.com/bkotos/listello/internal/listello-instance-context/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) Publish(event domain.Event) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.Event) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event domain.Event
func (_e *MockEventPublisher_Expecter) Publish(event any) *MockEventPublisher_Publish_Call {
	return &MockEventPublisher_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *MockEventPublisher_Publish_Call) Run(run func(event domain.Event)) *MockEventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Event
		if args[0] != nil {
			arg0 = args[0].(domain.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventPublisher_Publish_Call) Return(err error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_Publish_Call) RunAndReturn(run func(event domain.Event) error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListelloInstanceRepository creates a new instance of MockListelloInstanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListelloInstanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListelloInstanceRepository {
	mock := &MockListelloInstanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListelloInstanceRepository is an autogenerated mock type for the ListelloInstanceRepository type
type MockListelloInstanceRepository struct {
	mock.Mock
}

type MockListelloInstanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListelloInstanceRepository) EXPECT() *MockListelloInstanceRepository_Expecter {
	return &MockListelloInstanceRepository_Expecter{mock: &_m.Mock}
}

// GetInstance provides a mock function for the type MockListelloInstanceRepository
func (_mock *MockListelloInstanceRepository) GetInstance() (*domain.ListelloInstance, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *domain.ListelloInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*domain.ListelloInstance, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *domain.ListelloInstance); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ListelloInstance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListelloInstanceRepository_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type MockListelloInstanceRepository_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
func (_e *MockListelloInstanceRepository_Expecter) GetInstance() *MockListelloInstanceRepository_GetInstance_Call {
	return &MockListelloInstanceRepository_GetInstance_Call{Call: _e.mock.On("GetInstance")}
}

func (_c *MockListelloInstanceRepository_GetInstance_Call) Run(run func()) *MockListelloInstanceRepository_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListelloInstanceRepository_GetInstance_Call) Return(listelloInstance *domain.ListelloInstance, err error) *MockListelloInstanceRepository_GetInstance_Call {
	_c.Call.Return(listelloInstance, err)
	return _c
}

func (_c *MockListelloInstanceRepository_GetInstance_Call) RunAndReturn(run func() (*domain.ListelloInstance, error)) *MockListelloInstanceRepository_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockListelloInstanceRepository
func (_mock *MockListelloInstanceRepository) Save(instance domain.ListelloInstance) error {
	ret := _mock.Called(instance)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.ListelloInstance) error); ok {
		r0 = returnFunc(instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockListelloInstanceRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockListelloInstanceRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - instance domain.ListelloInstance
func (_e *MockListelloInstanceRepository_Expecter) Save(instance any) *MockListelloInstanceRepository_Save_Call {
	return &MockListelloInstanceRepository_Save_Call{Call: _e.mock.On("Save", instance)}
}

func (_c *MockListelloInstanceRepository_Save_Call) Run(run func(instance domain.ListelloInstance)) *MockListelloInstanceRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ListelloInstance
		if args[0] != nil {
			arg0 = args[0].(domain.ListelloInstance)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListelloInstanceRepository_Save_Call) Return(err error) *MockListelloInstanceRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockListelloInstanceRepository_Save_Call) RunAndReturn(run func(instance domain.ListelloInstance) error) *MockListelloInstanceRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
