// Code generated by tygo. DO NOT EDIT.

//////////
// source: item.go

/**
 * DefineItemRequest is the HTTP request body for defining an item on a list.
 */
export interface DefineItemRequest {
  title: string;
}
/**
 * ModifyItemTitleRequest is the HTTP request body for changing an item's title.
 */
export interface ModifyItemTitleRequest {
  title: string;
}
/**
 * MoveItemRequest is the HTTP request body for moving an item to another list.
 */
export interface MoveItemRequest {
  listID: string;
}
/**
 * CommentItemRequest is the HTTP request body for commenting on an item.
 */
export interface CommentItemRequest {
  body: string;
}
/**
 * ItemDto is the HTTP representation of an item.
 */
export interface ItemDto {
  ID: string;
  ListID: string;
  ParentID: string;
  Title: string;
  Description: string;
  DueDate: string;
  Tags: string[];
  Priority: string;
  State: string;
}

//////////
// source: item_comment.go

/**
 * ItemCommentDto is the HTTP representation of a comment on an item.
 */
export interface ItemCommentDto {
  ID: string;
  ItemID: string;
  UserID: string;
  UserName: string;
  Body: string;
  CreatedAt: string;
}

//////////
// source: list.go

/**
 * ListResponse is the HTTP representation of a list.
 */
export interface ListResponse {
  ID: string;
  Name: string;
}
/**
 * CreateFirstListRequest is the HTTP request body for creating the user's first list.
 */
export interface CreateFirstListRequest {
  name: string;
}

//////////
// source: space.go

/**
 * CreateSpaceRequest is the HTTP request body for creating a space.
 */
export interface CreateSpaceRequest {
  name: string;
}
/**
 * SpaceResponse is the HTTP representation of a space.
 */
export interface SpaceResponse {
  ID: string;
  Name: string;
}

//////////
// source: user.go

/**
 * CreateUserRequest is the HTTP request body for creating a user.
 */
export interface CreateUserRequest {
  name: string;
}
/**
 * UserResponse is the HTTP representation of a user.
 */
export interface UserResponse {
  ID: string;
  Name: string;
}
