// Code generated by tygo. DO NOT EDIT.

//////////
// source: item.go

/**
 * DefineItemRequest is the HTTP request body for defining an item on a list.
 */
export interface DefineItemRequest {
  title: string;
}
/**
 * ModifyItemTitleRequest is the HTTP request body for changing an item's title.
 */
export interface ModifyItemTitleRequest {
  title: string;
}
/**
 * ItemDto is the HTTP representation of an item.
 */
export interface ItemDto {
  ID: string;
  ListID: string;
  ParentID: string;
  Title: string;
  Description: string;
  DueDate: string;
  Tags: string[];
  Priority: string;
  State: string;
}

//////////
// source: list.go

/**
 * ListResponse is the HTTP representation of a list.
 */
export interface ListResponse {
  ID: string;
  Name: string;
}
