// Code generated by tygo. DO NOT EDIT.

//////////
// source: listello_instance.go

/**
 * SelectPersistenceLocationRequest is the HTTP request body for selecting a persistence location.
 */
export interface SelectPersistenceLocationRequest {
  location: string;
}
/**
 * ListelloInstanceResponse is the HTTP representation of a Listello instance.
 */
export interface ListelloInstanceResponse {
  HostingMode: string;
  PersistenceLocation: string;
  PersistenceState: string;
  SetupState: string;
}
