// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bkotos/listello/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockItemService creates a new instance of MockItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemService {
	mock := &MockItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemService is an autogenerated mock type for the ItemService type
type MockItemService struct {
	mock.Mock
}

type MockItemService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemService) EXPECT() *MockItemService_Expecter {
	return &MockItemService_Expecter{mock: &_m.Mock}
}

// DefineItem provides a mock function for the type MockItemService
func (_mock *MockItemService) DefineItem(listID string, title string) (domain.Item, error) {
	ret := _mock.Called(listID, title)

	if len(ret) == 0 {
		panic("no return value specified for DefineItem")
	}

	var r0 domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (domain.Item, error)); ok {
		return returnFunc(listID, title)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) domain.Item); ok {
		r0 = returnFunc(listID, title)
	} else {
		r0 = ret.Get(0).(domain.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(listID, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemService_DefineItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineItem'
type MockItemService_DefineItem_Call struct {
	*mock.Call
}

// DefineItem is a helper method to define mock.On call
//   - listID string
//   - title string
func (_e *MockItemService_Expecter) DefineItem(listID any, title any) *MockItemService_DefineItem_Call {
	return &MockItemService_DefineItem_Call{Call: _e.mock.On("DefineItem", listID, title)}
}

func (_c *MockItemService_DefineItem_Call) Run(run func(listID string, title string)) *MockItemService_DefineItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemService_DefineItem_Call) Return(item domain.Item, err error) *MockItemService_DefineItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemService_DefineItem_Call) RunAndReturn(run func(listID string, title string) (domain.Item, error)) *MockItemService_DefineItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListService creates a new instance of MockListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListService {
	mock := &MockListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListService is an autogenerated mock type for the ListService type
type MockListService struct {
	mock.Mock
}

type MockListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListService) EXPECT() *MockListService_Expecter {
	return &MockListService_Expecter{mock: &_m.Mock}
}

// CreateList provides a mock function for the type MockListService
func (_mock *MockListService) CreateList(name string) (domain.List, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateList")
	}

	var r0 domain.List
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.List, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.List); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(domain.List)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListService_CreateList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateList'
type MockListService_CreateList_Call struct {
	*mock.Call
}

// CreateList is a helper method to define mock.On call
//   - name string
func (_e *MockListService_Expecter) CreateList(name any) *MockListService_CreateList_Call {
	return &MockListService_CreateList_Call{Call: _e.mock.On("CreateList", name)}
}

func (_c *MockListService_CreateList_Call) Run(run func(name string)) *MockListService_CreateList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListService_CreateList_Call) Return(list domain.List, err error) *MockListService_CreateList_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockListService_CreateList_Call) RunAndReturn(run func(name string) (domain.List, error)) *MockListService_CreateList_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockListService
func (_mock *MockListService) GetAll() ([]domain.List, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.List
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]domain.List, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []domain.List); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.List)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockListService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockListService_Expecter) GetAll() *MockListService_GetAll_Call {
	return &MockListService_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockListService_GetAll_Call) Run(run func()) *MockListService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListService_GetAll_Call) Return(lists []domain.List, err error) *MockListService_GetAll_Call {
	_c.Call.Return(lists, err)
	return _c
}

func (_c *MockListService_GetAll_Call) RunAndReturn(run func() ([]domain.List, error)) *MockListService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockListService
func (_mock *MockListService) GetByID(id string) (domain.List, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.List
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.List, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.List); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(domain.List)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockListService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id string
func (_e *MockListService_Expecter) GetByID(id any) *MockListService_GetByID_Call {
	return &MockListService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockListService_GetByID_Call) Run(run func(id string)) *MockListService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListService_GetByID_Call) Return(list domain.List, err error) *MockListService_GetByID_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockListService_GetByID_Call) RunAndReturn(run func(id string) (domain.List, error)) *MockListService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
