// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package application_test

import (
	"github.com/bkotos/listello/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) Publish(event domain.Event) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.Event) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event domain.Event
func (_e *MockEventPublisher_Expecter) Publish(event any) *MockEventPublisher_Publish_Call {
	return &MockEventPublisher_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *MockEventPublisher_Publish_Call) Run(run func(event domain.Event)) *MockEventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Event
		if args[0] != nil {
			arg0 = args[0].(domain.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventPublisher_Publish_Call) Return(err error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_Publish_Call) RunAndReturn(run func(event domain.Event) error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemRepository creates a new instance of MockItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemRepository {
	mock := &MockItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemRepository is an autogenerated mock type for the ItemRepository type
type MockItemRepository struct {
	mock.Mock
}

type MockItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemRepository) EXPECT() *MockItemRepository_Expecter {
	return &MockItemRepository_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockItemRepository
func (_mock *MockItemRepository) GetAll(listID string) ([]domain.Item, error) {
	ret := _mock.Called(listID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]domain.Item, error)); ok {
		return returnFunc(listID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []domain.Item); ok {
		r0 = returnFunc(listID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(listID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockItemRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - listID string
func (_e *MockItemRepository_Expecter) GetAll(listID any) *MockItemRepository_GetAll_Call {
	return &MockItemRepository_GetAll_Call{Call: _e.mock.On("GetAll", listID)}
}

func (_c *MockItemRepository_GetAll_Call) Run(run func(listID string)) *MockItemRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockItemRepository_GetAll_Call) Return(items []domain.Item, err error) *MockItemRepository_GetAll_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockItemRepository_GetAll_Call) RunAndReturn(run func(listID string) ([]domain.Item, error)) *MockItemRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockItemRepository
func (_mock *MockItemRepository) Save(item domain.Item) error {
	ret := _mock.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.Item) error); ok {
		r0 = returnFunc(item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockItemRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockItemRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - item domain.Item
func (_e *MockItemRepository_Expecter) Save(item any) *MockItemRepository_Save_Call {
	return &MockItemRepository_Save_Call{Call: _e.mock.On("Save", item)}
}

func (_c *MockItemRepository_Save_Call) Run(run func(item domain.Item)) *MockItemRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Item
		if args[0] != nil {
			arg0 = args[0].(domain.Item)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockItemRepository_Save_Call) Return(err error) *MockItemRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockItemRepository_Save_Call) RunAndReturn(run func(item domain.Item) error) *MockItemRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListRepository creates a new instance of MockListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListRepository {
	mock := &MockListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListRepository is an autogenerated mock type for the ListRepository type
type MockListRepository struct {
	mock.Mock
}

type MockListRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListRepository) EXPECT() *MockListRepository_Expecter {
	return &MockListRepository_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockListRepository
func (_mock *MockListRepository) GetAll() ([]domain.List, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.List
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]domain.List, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []domain.List); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.List)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockListRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockListRepository_Expecter) GetAll() *MockListRepository_GetAll_Call {
	return &MockListRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockListRepository_GetAll_Call) Run(run func()) *MockListRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListRepository_GetAll_Call) Return(lists []domain.List, err error) *MockListRepository_GetAll_Call {
	_c.Call.Return(lists, err)
	return _c
}

func (_c *MockListRepository_GetAll_Call) RunAndReturn(run func() ([]domain.List, error)) *MockListRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockListRepository
func (_mock *MockListRepository) GetByID(id string) (domain.List, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.List
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.List, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.List); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(domain.List)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockListRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id string
func (_e *MockListRepository_Expecter) GetByID(id any) *MockListRepository_GetByID_Call {
	return &MockListRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockListRepository_GetByID_Call) Run(run func(id string)) *MockListRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListRepository_GetByID_Call) Return(list domain.List, err error) *MockListRepository_GetByID_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockListRepository_GetByID_Call) RunAndReturn(run func(id string) (domain.List, error)) *MockListRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockListRepository
func (_mock *MockListRepository) Save(list domain.List) error {
	ret := _mock.Called(list)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.List) error); ok {
		r0 = returnFunc(list)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockListRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockListRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - list domain.List
func (_e *MockListRepository_Expecter) Save(list any) *MockListRepository_Save_Call {
	return &MockListRepository_Save_Call{Call: _e.mock.On("Save", list)}
}

func (_c *MockListRepository_Save_Call) Run(run func(list domain.List)) *MockListRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.List
		if args[0] != nil {
			arg0 = args[0].(domain.List)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListRepository_Save_Call) Return(err error) *MockListRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockListRepository_Save_Call) RunAndReturn(run func(list domain.List) error) *MockListRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
