import type { AppState } from './types'

const day = 86400000
const now = Date.now()
const iso = (offset: number) => new Date(now + offset * day).toISOString().slice(0, 10)

export function seedState(): AppState {
  return {
    selectedListId: 'inbox',
    selectedItemId: null,
    tags: ['deep-work', 'errand', 'waiting', 'quick', 'home'],
    lists: [
      { id: 'work', name: 'Work' },
      { id: 'personal', name: 'Personal' },
      { id: 'reading', name: 'Reading' },
    ],
    events: [],
    items: [
      {
        id: 'i1',
        listId: 'inbox',
        title: 'Reply to the venue about the offsite',
        description: '',
        state: 'inbox',
        completed: false,
        priority: 'none',
        dueDate: null,
        tags: [],
        subtasks: [],
        comments: [],
        createdAt: now - day * 0.2,
      },
      {
        id: 'i2',
        listId: 'inbox',
        title: 'Idea: weekly review template',
        description: '',
        state: 'inbox',
        completed: false,
        priority: 'none',
        dueDate: null,
        tags: [],
        subtasks: [],
        comments: [],
        createdAt: now - day * 0.5,
      },
      {
        id: 'w1',
        listId: 'work',
        title: 'Ship the Q3 planning doc',
        description: 'Consolidate feedback from the team and finalize the roadmap section.',
        state: 'defined',
        completed: false,
        priority: 'high',
        dueDate: iso(2),
        tags: ['deep-work'],
        subtasks: [
          { id: 's1', title: 'Collect feedback', completed: true },
          { id: 's2', title: 'Draft roadmap section', completed: false },
          { id: 's3', title: 'Review with lead', completed: false },
        ],
        comments: [
          {
            id: 'c1',
            author: 'You',
            body: 'Waiting on numbers from analytics before finalizing.',
            createdAt: now - day * 1.1,
          },
        ],
        createdAt: now - day * 3,
      },
      {
        id: 'w2',
        listId: 'work',
        title: 'Prepare 1:1 notes',
        description: '',
        state: 'defined',
        completed: false,
        priority: 'medium',
        dueDate: iso(1),
        tags: ['quick'],
        subtasks: [],
        comments: [],
        createdAt: now - day * 1,
      },
      {
        id: 'w3',
        listId: 'work',
        title: 'Archive last sprint board',
        description: '',
        state: 'defined',
        completed: true,
        priority: 'low',
        dueDate: null,
        tags: [],
        subtasks: [],
        comments: [],
        createdAt: now - day * 5,
      },
      {
        id: 'p1',
        listId: 'personal',
        title: 'Book dentist appointment',
        description: '',
        state: 'defined',
        completed: false,
        priority: 'medium',
        dueDate: iso(4),
        tags: ['errand', 'waiting'],
        subtasks: [],
        comments: [],
        createdAt: now - day * 2,
      },
      {
        id: 'p2',
        listId: 'personal',
        title: 'Fix the leaky kitchen faucet',
        description: 'Pick up a replacement washer from the hardware store.',
        state: 'defined',
        completed: false,
        priority: 'low',
        dueDate: null,
        tags: ['home'],
        subtasks: [
          { id: 's4', title: 'Buy washer', completed: false },
          { id: 's5', title: 'Turn off water supply', completed: false },
        ],
        comments: [],
        createdAt: now - day * 6,
      },
      {
        id: 'r1',
        listId: 'reading',
        title: 'Domain-Driven Design — chapter 4',
        description: 'The chapter on isolating the domain.',
        state: 'defined',
        completed: false,
        priority: 'none',
        dueDate: null,
        tags: ['deep-work'],
        subtasks: [],
        comments: [],
        createdAt: now - day * 4,
      },
    ],
  }
}
